[build]
  command = "npm run production"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from="/api/*"
  to="/.netlify/functions/:splat"
  status=200

[build.environment]
SPOTIFY_CLIENT_ID = "9e2f907983ce45c481c8a5b29bcd683e"
SPOTIFY_CLIENT_SECRET = "0ea270d6c62c4f008279a2efaed9e811"
SPOTIFY_REFRESH_TOKEN = "AQDfMqvOTtUALlKZLdMUu_ol9ke-Zk-DUUAMDv-8evpeon4UKILWeMUtZAlJxwDpRsqjLD57MgZpG73Z63U2Roo_IJ0n2PPJe38QULKHSna8KVpO8CRZLoirTlBHIgSbpEs"
